services:
  localstack:
    image: localstack/localstack:3.6.0
    container_name: nexus-localstack
    networks:
      - nexus
    ports:
      - "4566:4566"
    env_file:
      - sandbox-tools/sandbox.env
    environment:
      - SERVICES=dynamodb,s3
      - HOSTNAME=localstack
      - LOCALSTACK_HOST=host.docker.internal
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - nexus

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: nexus-opensearch
    environment:
      - node.name=nexus-opensearch
      - cluster.name=nexus-opensearch-cluster
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx2048m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
    networks:
      - nexus
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: nexus-opensearch-dashboard
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - nexus
    depends_on:
      opensearch:
        condition: service_healthy

volumes:
  opensearch-data:
    driver: local

networks:
  nexus:
    driver: bridge